spring.datasource.url=jdbc:postgresql://210.119.146.225:5432/capstone
spring.datasource.username=capstone
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false
openai.api.key=